/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/sign/components/signSwitch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sign: typeof import('./src/components/sign/index.vue')['default']
    SignSwitch: typeof import('./src/components/sign/components/signSwitch.vue')['default']
    Sing: typeof import('./src/components/sing/signSwitch.vue')['default']
    SingIn: typeof import('./src/components/sign/components/singIn.vue')['default']
    SingUp: typeof import('./src/components/sign/components/singUp.vue')['default']
    Switch: typeof import('./src/components/sign/components/signSwitch.vue')['default']
  }
}
